/// <reference types="node" />
import { execSync } from "node:child_process";
import { writeFileSync, readFileSync } from "node:fs";

const OUTPUT_PATH = "./src/domains/users/db/auth-schema.generated.ts";
const BETTER_AUTH_CONFIG_PATH = "./src/infra/auth/better-auth.config.ts";
const HEADER = `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY ⚠️
 * Generated by 'pnpm auth:sync' at ${new Date().toISOString()}
 * Source of truth: apps/api/src/infra/auth/better-auth.config.ts
 */\n\n`;

console.log("🚀 Generating Better Auth schema...");
const configContent = readFileSync(BETTER_AUTH_CONFIG_PATH, "utf-8");
if (!configContent) {
  console.error(
    `❌ Failed to read Better Auth config at ${BETTER_AUTH_CONFIG_PATH}`,
  );
  process.exit(1);
}
console.log("✅ Better Auth config loaded successfully.");
console.log(
  "🔍 Config content preview:",
  configContent.substring(0, 200) + "...",
);
// 1. Run the CLI
execSync(
  `pnpm dlx auth@latest generate --config ./src/infra/auth/better-auth.config.ts --output ${OUTPUT_PATH} -y`,
);

// 2. Inject the Warning Header
const content = readFileSync(OUTPUT_PATH, "utf-8");
writeFileSync(OUTPUT_PATH, HEADER + content);

console.log(`✅ Schema updated and protected at ${OUTPUT_PATH}`);
